### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1) with Ruby 3.2.2 and Rails 6.1.4

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [zombocom/rack-timeout#208]
I get following error in production environment:
```
ArgumentError: wrong number of arguments (given 2, expected 1)
/usr/local/bundle/gems/rack-timeout-0.6.3/lib/rack/timeout/core.rb:69:in `initialize'
/usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/stack.rb:37:in `new'
/usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/stack.rb:37:in `build'
/usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/stack.rb:154:in `block in build'
/usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/stack.rb:150:in `each'
/usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/stack.rb:150:in `inject'
/usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/stack.rb:150:in `build'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/engine.rb:525:in `block in app'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/engine.rb:521:in `synchronize'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/engine.rb:521:in `app'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/application/finisher.rb:108:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/application.rb:391:in `initialize!'
/app/config/environment.rb:5:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/application.rb:367:in `require_environment!'
/usr/local/bundle/gems/railties-6.1.5/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sentry-ruby-5.5.0/lib/sentry/rake.rb:24:in `execute'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

Any ideas on how to fix this?

**Comment by iggant** [comment]
most likely problem is at a place where you insert this as a middleware. just make sure that you don't use old hash style of passing parameters

**Comment by wuputah** [comment]
Not enough information to debug this.
